version: '1.0.0'

services:
  bookers_postgres:
    image: postgres:16.2
    restart: always

    networks:
      - bookers_network

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: manager1
      POSTGRES_DB: bookers
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  bookers_network:
    driver: bridge